version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      context: requirements/mariadb
      args:
        - WORDPRESS_ROOT_PASSWORD=${WORDPRESS_ROOT_PASSWORD}
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: always
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      args:
        - CERTS_PATH=${CERTS_PATH}
        - CERTS_KEY=${CERTS_KEY}
    restart: always
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/rinacio/data/mysql
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/rinacio/data/wordpress